### PR TITLE
fix: Correct records sent to Kinesis Data Streams

### LINKED ISSUE #11: bug(stream): Records sent to Kinesis Data Streams are incorrect/corrupted
I'm seeing very interesting bug on awsbeat(filebeat 6.2.4 built w/ golang 1.10.2 for linux-amd64).

In nutshell, most of your records have invalid data.

To reproduce this issue, send 5 distinct records to the stream:

```console
$ for i in $(seq 5); do str="${str}${i}"; echo '{"mykey":"mykey4","myvalue":"'$i'"}' | tee -a logs/foo.log; done

{"mykey":"mykey4","myvalue":"1"}
{"mykey":"mykey4","myvalue":"2"}
{"mykey":"mykey4","myvalue":"3"}
{"mykey":"mykey4","myvalue":"4"}
{"mykey":"mykey4","myvalue":"5"}
```

Tail the stream:

```
kinesis-tail -stream kuokatest1
```

And then, you'll surprisingly see the last record(`{"mykey":"mykey4","myvalue":"5"}`) is repeated 5x times!

```
ApproximateArrivalTimestamp: 2018-05-22 09:45:51 +0000 UTC
Data: {"@timestamp":"2018-05-22T09:45:50.888Z","@metadata":{"beat":"filebeat","type":"doc","version":"6.2.4"},"mykey":"mykey4","myvalue":"5","source":"/mnt/log/foo.log","beat":{"name":"bd98d11e2e3b","hostname":"bd98d11e2e3b","version":"6.2.4"},"offset":165
SequenceNumber: 49584698524577875697015278055900189069985746083771318274
```

```
ApproximateArrivalTimestamp: 2018-05-22 09:45:51 +0000 UTC
Data: {"@timestamp":"2018-05-22T09:45:50.888Z","@metadata":{"beat":"filebeat","type":"doc","version":"6.2.4"},"mykey":"mykey4","myvalue":"5","source":"/mnt/log/foo.log","beat":{"name":"bd98d11e2e3b","hostname":"bd98d11e2e3b","version":"6.2.4"},"offset":165
SequenceNumber: 49584698524577875697015278055901397995805360712946024450
```

```
ApproximateArrivalTimestamp: 2018-05-22 09:45:51 +0000 UTC
Data: {"@timestamp":"2018-05-22T09:45:50.888Z","@metadata":{"beat":"filebeat","type":"doc","version":"6.2.4"},"mykey":"mykey4","myvalue":"5","source":"/mnt/log/foo.log","beat":{"name":"bd98d11e2e3b","hostname":"bd98d11e2e3b","version":"6.2.4"},"offset":165
SequenceNumber: 49584698524577875697015278055902606921624975342120730626
```

```
ApproximateArrivalTimestamp: 2018-05-22 09:45:51 +0000 UTC
Data: {"@timestamp":"2018-05-22T09:45:50.888Z","@metadata":{"beat":"filebeat","type":"doc","version":"6.2.4"},"mykey":"mykey4","myvalue":"5","source":"/mnt/log/foo.log","beat":{"name":"bd98d11e2e3b","hostname":"bd98d11e2e3b","version":"6.2.4"},"offset":165}
SequenceNumber: 49584698524577875697015278055903815847444589971295436802
```

```
ApproximateArrivalTimestamp: 2018-05-22 09:45:51 +0000 UTC
Data: {"@timestamp":"2018-05-22T09:45:50.888Z","@metadata":{"beat":"filebeat","type":"doc","version":"6.2.4"},"mykey":"mykey4","myvalue":"5","source":"/mnt/log/foo.log","beat":{"name":"bd98d11e2e3b","hostname":"bd98d11e2e3b","version":"6.2.4"},"offset":165}
SequenceNumber: 49584698524577875697015278055905024773264204600470142978
```

This is due to the misuse of `libbeat/outputs/codec/json` [here](https://github.com/s12v/awsbeats/blob/7ed4a0eefb493eeed3260520b8d5330d81a4109c/streams/client.go#L86-L106).

You should never do this:

```golang
serializedEvent, err := client.encoder.Encode(client.beatName, &event.Content)
// ...
return &kinesis.PutRecordsRequestEntry{Data: serializedEvent, PartitionKey: aws.String(partitionKey)}, nil
```

Instead you should do:

```golang
serializedEvent, err := client.encoder.Encode(client.beatName, &event.Content)
// ...
data := make([]byte, len(serializedEvent))
copy(data, serializedEvent)
return &kinesis.PutRecordsRequestEntry{Data: data, PartitionKey: aws.String(partitionKey)}, nil
```

The json codec seems to be designed that way, as we can see in [the implementation of the official kafka output plugin](https://github.com/elastic/beats/blob/5a6630a8bc9b9caf312978f57d1d9193bdab1ac7/libbeat/outputs/kafka/client.go#L163-L164), and [the json codec's usage of bytes.Buffer.Reset()](https://github.com/elastic/beats/blob/539c07eb952e44cd084ca070f3181eee771eaaa3/libbeat/outputs/codec/json/json.go#L71).

The same thing applies to awsbeat's [firehose](https://github.com/s12v/awsbeats/blob/master/firehose/client.go#L82-L92) plugin, as I have pointed out in #10.

### PR DESCRIPTION
**Pull request by mumoshu**
`glide up` wasnt necessarily but anyway I verified this to work with the latest version of aws-sdk-go

Fixes #11

Depends on #12. Plese see the last commit to review the change made in this PR.

### CODE REVIEW

**Comment by di1214** [comment]
@mumoshu can you add the fix to firehose as well?

**Comment by mumoshu** [comment]
@di1214 Sure! But it is really up to @s12v wether the fix is actually merged or not. He is the author of awsbeats. I don't have write permission to this repository 😉

File: streams/client.go [hunk 1]
```diff
@@ -83,14 +87,17 @@ func (client *client) mapEvents(events []publisher.Event) ([]*kinesis.PutRecords
...
+			logp.Critical("Unable to encode event: %v", err)
 			return nil, err
 		}
-
-		logp.Critical("Unable to encode event: %v", err)
-		return nil, err
+		// See https://github.com/elastic/beats/blob/5a6630a8bc9b9caf312978f57d1d9193bdab1ac7/libbeat/outputs/kafka/client.go#L163-L164
+		// You need to copy the byte data like this. Otherwise you see strange issues like all the records sent in a same batch has the same Data.
+		buf = make([]byte, len(serializedEvent))
+		copy(buf, serializedEvent)
```
Comment (s12v) [inline streams/client.go]: 👍
